import { AngularAppEngine, createRequestHandler } from '@angular/ssr';

import { SANITY_API_HOST, SANITY_IMAGE_CDN_URL } from './data/sanity.config';

const angularApp = new AngularAppEngine();

const SANITY_API_ORIGIN = `https://${SANITY_API_HOST}`;

/** Hosts pulled in by `@angular/youtube-player` when a video section is present. */
const YOUTUBE_API_ORIGIN = 'https://www.youtube.com';
const YOUTUBE_PLAYER_ORIGIN = 'https://www.youtube-nocookie.com';
const YOUTUBE_SCRIPT_ORIGIN = 'https://s.ytimg.com';
const YOUTUBE_THUMBNAIL_ORIGIN = 'https://i.ytimg.com';

/**
 * `'unsafe-inline'` is still required for scripts and styles: Angular emits
 * inline hydration/transfer-state scripts and injects component styles as inline
 * `<style>` blocks. Tightening this means switching to the builder's hash-based
 * `security.autoCsp` option, which is still in preview.
 */
const CONTENT_SECURITY_POLICY = [
  `default-src 'self'`,
  `base-uri 'self'`,
  `object-src 'none'`,
  `form-action 'self'`,
  `frame-ancestors 'none'`,
  `script-src 'self' 'unsafe-inline' ${YOUTUBE_API_ORIGIN} ${YOUTUBE_SCRIPT_ORIGIN}`,
  `style-src 'self' 'unsafe-inline'`,
  `img-src 'self' data: ${SANITY_IMAGE_CDN_URL} ${YOUTUBE_THUMBNAIL_ORIGIN}`,
  `font-src 'self'`,
  `connect-src 'self' ${SANITY_API_ORIGIN}`,
  `frame-src ${YOUTUBE_PLAYER_ORIGIN} ${YOUTUBE_API_ORIGIN}`,
  `upgrade-insecure-requests`,
].join('; ');

/**
 * Security headers for every response this Worker produces.
 *
 * `public/_headers` only covers responses served straight from static assets:
 * Cloudflare does not apply it to responses generated by Worker code, and with
 * SSR that is every HTML page on the site.
 */
const SECURITY_HEADERS: Readonly<Record<string, string>> = {
  'Content-Security-Policy': CONTENT_SECURITY_POLICY,
  'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'DENY',
  'Referrer-Policy': 'strict-origin-when-cross-origin',
  'Cross-Origin-Opener-Policy': 'same-origin',
  'Permissions-Policy': [
    'accelerometer=()',
    'camera=()',
    'geolocation=()',
    'gyroscope=()',
    'magnetometer=()',
    'microphone=()',
    'payment=()',
    'usb=()',
  ].join(', '),
};

/** Response headers are immutable, so the response is rebuilt around a new set. */
function withSecurityHeaders(response: Response, requestUrl: string): Response {
  const headers = new Headers(response.headers);

  for (const [name, value] of Object.entries(SECURITY_HEADERS)) {
    headers.set(name, value);
  }

  // Keep the deploy preview out of search results. This cannot live in
  // `_headers` either, for the same reason the security headers cannot.
  if (new URL(requestUrl).hostname.endsWith('.workers.dev')) {
    headers.set('X-Robots-Tag', 'noindex');
  }

  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}

export const reqHandler = createRequestHandler(async (request) => {
  const response = await angularApp.handle(request);

  return withSecurityHeaders(
    response ?? new Response('Page not found.', { status: 404 }),
    request.url,
  );
});

export default { fetch: reqHandler };
