import { AngularAppEngine, createRequestHandler } from '@angular/ssr';

import { ContactEnv, handleContactRequest } from './contact.endpoint';
import { CONTACT_ENDPOINT } from './shared/contact/contact.model';
import { SANITY_API_HOST, SANITY_IMAGE_CDN_URL } from './data/sanity.config';
import { TURNSTILE_ORIGIN } from './shared/turnstile/turnstile.config';

const angularApp = new AngularAppEngine();

const SANITY_API_ORIGIN = `https://${SANITY_API_HOST}`;

/** Hosts pulled in by `@angular/youtube-player` when a video section is present. */
const YOUTUBE_API_ORIGIN = 'https://www.youtube.com';
const YOUTUBE_PLAYER_ORIGIN = 'https://www.youtube-nocookie.com';
const YOUTUBE_SCRIPT_ORIGIN = 'https://s.ytimg.com';
const YOUTUBE_THUMBNAIL_ORIGIN = 'https://i.ytimg.com';

/**
 * `'unsafe-inline'` is still required for scripts and styles: Angular emits
 * inline hydration/transfer-state scripts and injects component styles as inline
 * `<style>` blocks. Tightening this means switching to the builder's hash-based
 * `security.autoCsp` option, which is still in preview.
 *
 * `TURNSTILE_ORIGIN` appears three times over because the anti-robot widget on
 * the contact page loads a script, mounts an iframe, and reports its outcome back
 * to Cloudflare.
 */
const CONTENT_SECURITY_POLICY = [
  `default-src 'self'`,
  `base-uri 'self'`,
  `object-src 'none'`,
  `form-action 'self'`,
  `frame-ancestors 'none'`,
  `script-src 'self' 'unsafe-inline' ${TURNSTILE_ORIGIN} ${YOUTUBE_API_ORIGIN} ${YOUTUBE_SCRIPT_ORIGIN}`,
  `style-src 'self' 'unsafe-inline'`,
  `img-src 'self' data: ${SANITY_IMAGE_CDN_URL} ${YOUTUBE_THUMBNAIL_ORIGIN}`,
  `font-src 'self'`,
  `connect-src 'self' ${SANITY_API_ORIGIN} ${TURNSTILE_ORIGIN}`,
  `frame-src ${TURNSTILE_ORIGIN} ${YOUTUBE_PLAYER_ORIGIN} ${YOUTUBE_API_ORIGIN}`,
  `upgrade-insecure-requests`,
].join('; ');

/**
 * Security headers for every response this Worker produces.
 *
 * `public/_headers` only covers responses served straight from static assets:
 * Cloudflare does not apply it to responses generated by Worker code, and with
 * SSR that is every HTML page on the site.
 */
const SECURITY_HEADERS: Readonly<Record<string, string>> = {
  'Content-Security-Policy': CONTENT_SECURITY_POLICY,
  'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'DENY',
  'Referrer-Policy': 'strict-origin-when-cross-origin',
  'Cross-Origin-Opener-Policy': 'same-origin',
  'Permissions-Policy': [
    'accelerometer=()',
    'camera=()',
    'geolocation=()',
    'gyroscope=()',
    'magnetometer=()',
    'microphone=()',
    'payment=()',
    'usb=()',
  ].join(', '),
};

/** Response headers are immutable, so the response is rebuilt around a new set. */
function withSecurityHeaders(response: Response, requestUrl: string): Response {
  const headers = new Headers(response.headers);

  for (const [name, value] of Object.entries(SECURITY_HEADERS)) {
    headers.set(name, value);
  }

  // Keep the deploy preview out of search results. This cannot live in
  // `_headers` either, for the same reason the security headers cannot.
  if (new URL(requestUrl).hostname.endsWith('.workers.dev')) {
    headers.set('X-Robots-Tag', 'noindex');
  }

  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}

/**
 * The single path through the Worker, whichever entry point called it.
 *
 * @param env Cloudflare bindings and secrets. Only the default export receives
 *   them: `reqHandler` is called by the Angular dev server with the request
 *   alone, so the contact endpoint answers 503 under `ng serve`.
 */
async function handle(request: Request, env?: ContactEnv): Promise<Response> {
  // Intercepted before Angular, which would otherwise render the 404 page for it.
  if (new URL(request.url).pathname === CONTACT_ENDPOINT) {
    return withSecurityHeaders(await handleContactRequest(request, env), request.url);
  }

  const response = await angularApp.handle(request);

  return withSecurityHeaders(
    response ?? new Response('Page not found.', { status: 404 }),
    request.url,
  );
}

/** Used by the Angular dev server, which looks this export up by name. */
export const reqHandler = createRequestHandler((request) => handle(request));

/**
 * Used by workerd. Declared separately from `reqHandler` because Angular's
 * `RequestHandlerFunction` takes only a request, and the contact endpoint needs
 * the `env` argument the runtime passes alongside it.
 */
export default {
  fetch: (request: Request, env: ContactEnv): Promise<Response> => handle(request, env),
};
